spring.datasource.url=jdbc:postgresql://quiz_db_xpya_user:WhCog1jh1L8Khl9kix6NZIkH4g4IyTo8@dpg-d8e3d6favr4c738aorug-a/quiz_db_xpya>
spring.datasource.username=<quiz_db_xpya_user>
spring.datasource.password=<WhCog1jh1L8Khl9kix6NZIkH4g4IyTo8>
spring.datasource.driver-class-name=org.postgresql.Driver

# Force Hibernate to skip metadata detection and use PostgreSQL directly
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database initialization
spring.jpa.hibernate.ddl-auto=update